# Generated by Django 4.2.7 on 2023-11-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0002_grade_alter_album_options_album_img_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coletanea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_coletanea', models.CharField(help_text='Defina um nome para a sua coletânea de discos.', max_length=25)),
                ('email', models.EmailField(help_text='Usaremos o seu email apenas para enviar o link da sua coletânea por email.', max_length=254)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='Data e hora da última visita')),
                ('albums', models.ManyToManyField(blank=True, to='albums.album', verbose_name='Albums')),
            ],
            options={
                'verbose_name': 'Coletânea',
                'verbose_name_plural': 'Coletâneas',
            },
        ),
    ]
