# Generated by Django 4.0.4 on 2022-06-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do(a) artista')),
                ('wikipedia_link', models.URLField(blank=True, null=True, verbose_name='Link da wikipedia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data e hora da última atualização')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo do disco')),
                ('ano', models.IntegerField(verbose_name='Ano de lançamento')),
                ('wikipedia_link', models.URLField(blank=True, null=True, verbose_name='Link da wikipedia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data e hora da última atualização')),
                ('artista', models.ManyToManyField(blank=True, to='albums.artista', verbose_name='Artista(s)')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ('-ano',),
            },
        ),
    ]
