# Generated by Django 4.2.7 on 2023-11-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Atribua uma nota a este album', null=True, verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('-pk',), 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AddField(
            model_name='album',
            name='img_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link da capa do album'),
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do album'),
        ),
        migrations.AddField(
            model_name='album',
            name='grades',
            field=models.ManyToManyField(to='albums.grade'),
        ),
    ]
